"""Tests for the orchestrator-agent rename migration helpers."""

from __future__ import annotations

from pathlib import Path
from unittest.mock import MagicMock, patch

from nanobot.cli.commands import app
from typer.testing import CliRunner

from mc.contexts.agents.orchestrator_rename import rename_runtime_home

runner = CliRunner()


def test_rename_runtime_home_renames_agent_dirs_and_updates_files(tmp_path: Path) -> None:
    runtime_home = tmp_path / ".nanobot"
    agent_dir = runtime_home / "agents" / "lead-agent"
    board_agent_dir = runtime_home / "boards" / "default" / "agents" / "lead-agent"
    task_dir = runtime_home / "tasks" / "task-1"

    agent_dir.mkdir(parents=True)
    board_agent_dir.mkdir(parents=True)
    task_dir.mkdir(parents=True)

    (agent_dir / "config.yaml").write_text(
        "name: lead-agent\nrole: Lead Orchestrator\nprompt: You are the lead agent for Mission Control.\n"
    )
    (agent_dir / "SOUL.md").write_text("# Soul\n\nI am Lead Agent, a nanobot agent.\n")
    (board_agent_dir / ".mcp.json").write_text('{"agent":"lead-agent","mode":"lead_agent"}\n')
    (task_dir / "THREAD_JOURNAL.md").write_text(
        "\n".join(
            [
                "# Thread Journal",
                "- Assigned Agent: lead-agent",
                "- Plan Generated By: lead-agent",
                "## Thread Events",
                "### 2026-03-16T12:00:00Z | lead-agent | lead_agent_chat",
            ]
        )
        + "\n",
        encoding="utf-8",
    )

    result = rename_runtime_home(runtime_home, dry_run=False)

    renamed_agent_dir = runtime_home / "agents" / "orchestrator-agent"
    renamed_board_agent_dir = runtime_home / "boards" / "default" / "agents" / "orchestrator-agent"
    assert renamed_agent_dir.is_dir()
    assert renamed_board_agent_dir.is_dir()
    config_text = (renamed_agent_dir / "config.yaml").read_text(encoding="utf-8")
    assert "orchestrator-agent" in config_text
    assert "Orchestrator Agent" in config_text
    assert "lead agent" not in config_text
    soul_text = (renamed_agent_dir / "SOUL.md").read_text(encoding="utf-8")
    assert "Orchestrator Agent" in soul_text
    assert "Lead Agent" not in soul_text
    assert "orchestrator_agent" in (renamed_board_agent_dir / ".mcp.json").read_text(
        encoding="utf-8"
    )
    journal_text = (task_dir / "THREAD_JOURNAL.md").read_text(encoding="utf-8")
    assert "| orchestrator-agent | orchestrator_agent_chat" in journal_text
    assert not result["conflicts"]
    assert len(result["renamed_dirs"]) == 2
    assert len(result["updated_files"]) == 4


def test_rename_runtime_home_aborts_on_directory_conflict(tmp_path: Path) -> None:
    runtime_home = tmp_path / ".nanobot"
    legacy_dir = runtime_home / "agents" / "lead-agent"
    target_dir = runtime_home / "agents" / "orchestrator-agent"
    legacy_dir.mkdir(parents=True)
    target_dir.mkdir(parents=True)
    (target_dir / "config.yaml").write_text("name: orchestrator-agent\nrole: Lead Orchestrator\n")

    result = rename_runtime_home(runtime_home, dry_run=False)

    assert result["renamed_dirs"] == []
    assert result["updated_files"] == []
    assert result["conflicts"]
    assert legacy_dir.is_dir()
    assert target_dir.is_dir()
    assert "Lead Orchestrator" in (target_dir / "config.yaml").read_text(encoding="utf-8")


def test_rename_lead_agent_cli_reports_dry_run_summary(tmp_path: Path) -> None:
    fake_bridge = MagicMock()
    fake_bridge.close = MagicMock()
    fake_bridge.mutation.return_value = {"changes": {"agents": 1, "tasks": 2}, "conflicts": []}

    with patch("mc.cli._get_bridge", return_value=fake_bridge):
        result = runner.invoke(
            app,
            [
                "mc",
                "agents",
                "rename-lead-agent",
                "--dry-run",
                "--runtime-home",
                str(tmp_path / ".nanobot"),
            ],
        )

    assert result.exit_code == 0
    assert "DRY RUN" in result.stdout
    assert "Convex backfill" in result.stdout
    assert "agents: 1" in result.stdout
    fake_bridge.close.assert_called_once()
