"""Migration helpers for renaming the legacy lead agent to orchestrator-agent."""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING, Any

from mc.infrastructure.runtime_home import get_runtime_home

if TYPE_CHECKING:
    from mc.bridge import ConvexBridge

LEGACY_AGENT_NAME = "lead-agent"
ORCHESTRATOR_AGENT_NAME = "orchestrator-agent"

_STRUCTURED_FILE_REPLACEMENTS = (
    ("lead_agent_chat", "orchestrator_agent_chat"),
    ("lead_agent", "orchestrator_agent"),
    ("lead-agent", "orchestrator-agent"),
    ("Lead Agent", "Orchestrator Agent"),
    ("lead agent", "Orchestrator Agent"),
    ("Lead Orchestrator", "Orchestrator Agent"),
    ("Orchestrator Agent — Orchestrator", "Orchestrator Agent"),
    ("Orchestrator Agent -- Orchestrator", "Orchestrator Agent"),
)

_THREAD_JOURNAL_REPLACEMENTS = (
    ("- Assigned Agent: lead-agent", "- Assigned Agent: orchestrator-agent"),
    ("- Plan Generated By: lead-agent", "- Plan Generated By: orchestrator-agent"),
    ("| lead-agent |", "| orchestrator-agent |"),
    ("| lead_agent_chat", "| orchestrator_agent_chat"),
)


def _replace_tokens(text: str, replacements: tuple[tuple[str, str], ...]) -> str:
    updated = text
    for old, new in replacements:
        updated = updated.replace(old, new)
    return updated


def _rewrite_text_file(
    path: Path,
    *,
    dry_run: bool,
    replacements: tuple[tuple[str, str], ...],
) -> bool:
    if not path.is_file():
        return False
    original = path.read_text(encoding="utf-8")
    updated = _replace_tokens(original, replacements)
    if updated == original:
        return False
    if not dry_run:
        path.write_text(updated, encoding="utf-8")
    return True


def _planned_agent_dir_pairs(runtime_home: Path) -> list[tuple[Path, Path]]:
    pairs = [
        (
            runtime_home / "agents" / LEGACY_AGENT_NAME,
            runtime_home / "agents" / ORCHESTRATOR_AGENT_NAME,
        )
    ]
    boards_dir = runtime_home / "boards"
    if boards_dir.is_dir():
        for board_dir in sorted(path for path in boards_dir.iterdir() if path.is_dir()):
            pairs.append(
                (
                    board_dir / "agents" / LEGACY_AGENT_NAME,
                    board_dir / "agents" / ORCHESTRATOR_AGENT_NAME,
                )
            )
    return pairs


def rename_runtime_home(
    runtime_home: Path | None = None,
    *,
    dry_run: bool,
) -> dict[str, list[str]]:
    """Rename load-bearing runtime-home state from lead-agent to orchestrator-agent."""
    root = runtime_home or get_runtime_home()
    renamed_dirs: list[str] = []
    updated_files: list[str] = []
    conflicts: list[str] = []

    for source_dir, target_dir in _planned_agent_dir_pairs(root):
        if source_dir.exists() and target_dir.exists():
            conflicts.append(f"Directory conflict: {source_dir} -> {target_dir}")

    if conflicts:
        return {
            "renamed_dirs": renamed_dirs,
            "updated_files": updated_files,
            "conflicts": conflicts,
        }

    candidate_agent_dirs: list[Path] = []
    for source_dir, target_dir in _planned_agent_dir_pairs(root):
        if source_dir.exists():
            renamed_dirs.append(f"{source_dir} -> {target_dir}")
            if not dry_run:
                target_dir.parent.mkdir(parents=True, exist_ok=True)
                source_dir.rename(target_dir)
                candidate_agent_dirs.append(target_dir)
            else:
                candidate_agent_dirs.append(source_dir)
        elif target_dir.exists():
            candidate_agent_dirs.append(target_dir)

    for agent_dir in candidate_agent_dirs:
        for relative_name in ("config.yaml", ".mcp.json", "SOUL.md"):
            file_path = agent_dir / relative_name
            if _rewrite_text_file(
                file_path,
                dry_run=dry_run,
                replacements=_STRUCTURED_FILE_REPLACEMENTS,
            ):
                updated_files.append(str(file_path))

    tasks_dir = root / "tasks"
    if tasks_dir.is_dir():
        for journal_path in sorted(tasks_dir.rglob("THREAD_JOURNAL.md")):
            if _rewrite_text_file(
                journal_path,
                dry_run=dry_run,
                replacements=_THREAD_JOURNAL_REPLACEMENTS,
            ):
                updated_files.append(str(journal_path))

    return {
        "renamed_dirs": renamed_dirs,
        "updated_files": updated_files,
        "conflicts": conflicts,
    }


def migrate_lead_agent_to_orchestrator(
    bridge: ConvexBridge,
    *,
    runtime_home: Path | None = None,
    dry_run: bool,
) -> dict[str, Any]:
    """Run the Convex backfill plus runtime-home rename in one idempotent operation."""
    convex_result = bridge.mutation(
        "agents:renameLeadAgentToOrchestrator",
        {"dry_run": dry_run},
    )
    runtime_result = rename_runtime_home(runtime_home, dry_run=dry_run)
    return {
        "convex": convex_result,
        "runtime_home": runtime_result,
    }
